# Generated by Django 4.2.13 on 2024-07-15 16:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('user_phone', models.IntegerField(blank=True, null=True, verbose_name='Số điện thoại khách hàng')),
                ('user_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ khách hàng')),
                ('user_birthday', models.DateField(blank=True, null=True, verbose_name='Ngày sinh của khách')),
                ('user_avatar', models.ImageField(blank=True, default='user_image/user_empty.png', null=True, upload_to='user_image')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vai trò tài khoản')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Quản lý tài khoản Đăng Nhập',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên danh mục')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Danh Mục',
                'ordering': ['categories_id'],
            },
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('clock_id', models.AutoField(primary_key=True, serialize=False)),
                ('clock_name', models.CharField(max_length=255, verbose_name='Tên đồng hồ')),
                ('describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Giá sản phẩm')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số lượng hiện có')),
                ('sex', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giới tính')),
                ('designs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kiểu dáng')),
                ('glass_surface', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mặt kính')),
                ('diameter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường kính')),
                ('face_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Màu mặt')),
                ('shell_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chất liệu vỏ')),
                ('water_resistance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Độ chịu nước')),
                ('other_function', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tính năng khác')),
                ('brand_origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xuất sứ thương hiệu')),
                ('warranty_genuine', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bảo hành chính hãng')),
                ('percent_discount', models.IntegerField(blank=True, default=10, null=True, verbose_name='Phần trăm giảm giá (%)')),
                ('price_has_decreased', models.IntegerField(blank=True, default=10, null=True, verbose_name='Giá sau khi giảm')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_categories', to='website.categories')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm đồng hồ',
                'ordering': ['clock_id'],
            },
        ),
        migrations.CreateModel(
            name='Machine_type',
            fields=[
                ('machine_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Loại máy')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Loại máy đồng hồ',
                'ordering': ['machine_type_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, verbose_name='Mã đơn hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Số điện thoại khách hàng')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ khách hàng')),
                ('note', models.CharField(max_length=255, verbose_name='Ghi chú')),
                ('total_amount', models.IntegerField(default=1, verbose_name='Tổng số lượng sản phẩm')),
                ('total_pay', models.IntegerField(blank=True, null=True, verbose_name='Tổng tiền')),
                ('status', models.CharField(blank=True, choices=[('Chờ Xác nhận', 'Chờ Xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đang giao hàng', 'Đang giao hàng'), ('Đã giao hàng', 'Đã giao hàng')], default='Chờ Xác nhận', max_length=100, null=True, verbose_name='Trạng thái đơn hàng')),
                ('payment_type', models.CharField(blank=True, choices=[('Thanh toán khi nhận', 'Thanh toán khi nhận'), ('Thanh toán bằng thẻ', 'Thanh toán bằng thẻ'), ('Trả góp', 'Trả góp')], default='Thanh toán khi nhận', max_length=100, null=True, verbose_name='Loại thanh toán')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Đơn Hàng',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(max_length=255, verbose_name='Nội dung')),
                ('post_date', models.DateField(auto_now=True, verbose_name='Ngày đăng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post_image', verbose_name='Hình bài đăng')),
            ],
            options={
                'verbose_name_plural': 'Bài đăng',
                'ordering': ['post_id'],
            },
        ),
        migrations.CreateModel(
            name='Price_limit',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_limit_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mức giá')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Mức giá đồng hồ',
                'ordering': ['price_id'],
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotions_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotions_code', models.IntegerField(blank=True, null=True, verbose_name='Mã giảm giá')),
                ('promotions_name', models.CharField(blank=True, null=True, verbose_name='Têm mã giảm giá')),
                ('promotions_discount', models.IntegerField(verbose_name='gía trị giảm')),
                ('promotions_discount_percent', models.IntegerField(verbose_name='Phần trăm giảm giá')),
                ('amount', models.IntegerField(null=True, verbose_name='Số lượng')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian tồn tại đến ngày nào')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian tồn tại đến ngày nào')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Phiếu Giảm Giá',
                'ordering': ['promotions_id'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Phong cách')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Phong cách đồng hồ',
                'ordering': ['style_id'],
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('trademark_id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Trademark_image', verbose_name='Ảnh đại diện')),
                ('trademark_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên thương hiệu')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thương hiệu đồng hồ',
                'ordering': ['trademark_id'],
            },
        ),
        migrations.CreateModel(
            name='Wire_material',
            fields=[
                ('wire_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('wire_material_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên Chất liệu dây')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Chất liệu dây',
                'ordering': ['wire_material_id'],
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('orderdetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Số lượng')),
                ('total_money', models.IntegerField(blank=True, null=True, verbose_name='Thành tiền')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockdetails', to='website.clock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='website.order')),
            ],
            options={
                'verbose_name_plural': 'Các mặt hàng trong đơn hàng',
                'ordering': ['orderdetails_id'],
            },
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos', verbose_name='Video')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('belong_clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_video_clock', to='website.clock')),
            ],
            options={
                'verbose_name_plural': 'Video',
                'ordering': ['video_id'],
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='Ảnh ')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('belong_clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_image_clock', to='website.clock')),
            ],
            options={
                'verbose_name_plural': 'Hình ảnh',
                'ordering': ['image_id'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('installment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Só tiền trong 1 kỳ')),
                ('number_of_payments', models.IntegerField(blank=True, null=True, verbose_name='Số kỳ trả góp')),
                ('payments_fulfilled', models.IntegerField(blank=True, null=True, verbose_name='Trả góp đã hoàn thành')),
                ('payment_by_installment', models.IntegerField(blank=True, null=True, verbose_name='Số kỳ còn lại')),
                ('settled', models.BooleanField(default=False, verbose_name='Tất toán chưa')),
                ('status', models.CharField(blank=True, choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đang chạy', 'Đang chạy'), ('Đã tất toán', 'Đã tất toán'), ('Thanh toán trễ', 'Thanh toán trễ')], default='Chờ Xác nhận', max_length=100, null=True, verbose_name='Trang thái đơn trả góp')),
                ('clock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Installment_Clock', to='website.clock')),
                ('orderdetails_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Installment_Orderdetails', to='website.orderdetails')),
            ],
            options={
                'verbose_name_plural': 'Trả góp',
                'ordering': ['installment_id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmt', models.CharField(max_length=255, verbose_name='Bình Luận')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Điểm số')),
                ('clock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Clock', to='website.clock')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commnet_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bình luận',
                'ordering': ['comment_id'],
            },
        ),
        migrations.AddField(
            model_name='clock',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_machine_type', to='website.machine_type'),
        ),
        migrations.AddField(
            model_name='clock',
            name='price_limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_price_limit', to='website.price_limit'),
        ),
        migrations.AddField(
            model_name='clock',
            name='trademark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_trademark', to='website.trademark'),
        ),
        migrations.AddField(
            model_name='clock',
            name='wire_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_wire_material', to='website.wire_material'),
        ),
    ]
