# Generated by Django 4.2.13 on 2024-07-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
