# Generated by Django 4.2.13 on 2024-07-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_installment_installment_period_image_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment_period',
            name='period_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã Thanh Toán'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Từ Chối', 'Từ Chối'), ('Đang Chạy', 'Đang Chạy'), ('Đã tất toán', 'Đã tất toán'), ('Thanh toán trễ', 'Thanh toán trễ')], default='Chờ Xác nhận', max_length=100, null=True, verbose_name='Trang thái đơn trả góp'),
        ),
    ]
