# Generated by Django 4.2.13 on 2024-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_installment_period_period_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='installment_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã Đơn hàng trả góp'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Thanh toán khi nhận', 'Thanh toán khi nhận'), ('Thanh toán online', 'Thanh toán online'), ('Trả góp', 'Trả góp')], default='Thanh toán khi nhận', max_length=100, null=True, verbose_name='Loại thanh toán'),
        ),
    ]
