# Generated by Django 4.2.13 on 2024-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_installment_installment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='amount_settled',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số tiền tất toán'),
        ),
    ]
