# Generated by Django 4.2.13 on 2024-07-31 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_promotions', to='website.promotions'),
        ),
    ]
