# Generated by Django 4.2.13 on 2024-08-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_order_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment_period',
            old_name='period_id',
            new_name='installment_id',
        ),
    ]
