# Generated by Django 4.2.13 on 2024-08-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_period_id_installment_period_installment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tổng tiền thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='đơn giá'),
        ),
    ]
