# Generated by Django 4.2.13 on 2024-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(blank=True, default='Chờ Xác nhận', max_length=100, null=True, verbose_name='Trang thái đơn trả góp'),
        ),
    ]
