# Generated by Django 5.1 on 2024-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_installment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại giao hàng'),
        ),
    ]
