# Generated by Django 5.1 on 2024-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment_period',
            name='congchuoi',
            field=models.CharField(blank=True, null=True, verbose_name='cong chuoi'),
        ),
    ]
