# Generated by Django 5.1 on 2024-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_installment_period_congchuoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment_period',
            name='congchuoi',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='cong chuoi'),
        ),
    ]
